grails-app/domain/blagger/Post.groovy
package blagger

class Post {

    String title
    String email
    String content
    Date dateCreated
    Date lastUpdated

    static constraints = {
    }

    static mapping = {
        content type: 'text'
    }

}

grails-app/controllers/blagger/BlogController.groovy
package blagger

class BlogController {

    static defaultAction = "list"

    def list() {
        [posts: Post.list().sort { lhs, rhs -> rhs.id <=> lhs.id }]
    }

    def create() {
        [post: new Post(params)]
    }

    def createPost() {

        def aPost = new Post(params)

        if (!aPost.save(flush: true)) {
            render(view: "create", model: [post: aPost])
            return
        }

        redirect(action: 'list')
    }
}

grails-app/views/blog/create.gsp
<html>

<r:script>

    $('input[name=title]').focus();

</r:script>

<head></head>

<body>

    <g:form controller="blog" action="createPost" class="form-horizontal">

        <fieldset>
        <legend>Blag about something new!</legend>

            <div class="control-group">
                <label class="control-label" for="title">Title</label>
                <div class="controls">
                    <g:textField name="title" value="${post?.title}" placeholder="My first blag post..." class="input-block-level"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="title">Your email</label>
                <div class="controls">
                    <g:textField name="email" value="${post?.email}" placeholder="test@test.com" class="input-block-level"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="content">The blag</label>
                <div class="controls">
                    <g:textArea name="content" value="${post?.content}" placeholder="The blag..." class="input-block-level" rows="10"/>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn">Submit</button>
                </div>
            </div>

        </fieldset>

    </g:form>

</body>

</html>

grails-app/views/blog/list.gsp
<html>

<head></head>

<body>

<g:each in="${posts}" var="post">

    <h1>${post.title}</h1>
    <p class="lead">By <span class="text-info">${post.email}</span> on <g:formatDate format="dd/MM/yyyy @ HH:mm" date="${post.dateCreated}"/></p>

    ${post.content}

    <hr/>

</g:each>

</body>

</html>

grails-app/views/layouts/blog.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title><g:layoutTitle default="Blagger" /></title>
    <g:layoutHead />

    <r:require module="blog"/>

    <r:layoutResources/>
</head>
<body>

<header class="jumbotron subhead" id="overview">
    <div class="container">
        <g:link controller="blog" action="list"><h1>Blagger</h1></g:link>
        <p class="lead">Blogging for blaggers; it's what people think you know that matters</p>

        <g:link controller="blog" action="create" class="btn btn-large btn-primary">Blag something...</g:link>
    </div>
</header>

<div class="container">

    <g:layoutBody />

</div>

<r:layoutResources/>
</body>
</html>